### ISSUE TITLE
It's a segmentation error when dealing with quotation marks

### ISSUE THREAD

**Issue by codertimeless** [MichaelAquilina/flake8-spellcheck#17]
In dictionary, class's -> classs
Cause typo  'classs' pass check.
Please fix this problem when you have time :)

`# __init__.py lines of 118
        # Hacky way of getting dictionary with symbols stripped
        self.no_symbols = set(w.replace("'", "") for w in self.words)`

**Comment by MichaelAquilina** [comment]
@codertimeless could you provide an example of where this would fail?

**Comment by codertimeless** [comment]
For example, "request_classs" can be checked, but obviously "classs" is a misspelling.
This is because there is a "class' s" in your dictionary, and the "'" is removed from the above line of code, resulting in the word "classes" in the dictionary.

**Comment by MichaelAquilina** [comment]
> For example, "request_classs" can be checked, but obviously "classs" is a misspelling.
This is because there is a "class' s" in your dictionary, and the "'" is removed from the above line of code, resulting in the word "classes" in the dictionary.

Thanks for this. It's clear to me now what you are referring to :)

**Comment by MichaelAquilina** [comment]
Fixed by 586956f18eaa6e91602f0f00cba48d9175aea852 in version 0.10.0

Let me know if this is still an issue for you

**Comment by codertimeless** [comment]
Happy new year！
The new version of the plug-in works great! My team and I have been using it.
However, as a Django engineer, I need to add too many words (some method, class and variable names in Django) to the white list. I think this is a big burden for other people who use this plug-in. So, I think we can sort out a part of it and add it to the dictionary of the plug-in for other people's convenience.

**Comment by MichaelAquilina** [comment]
> Happy new year！

Thanks you too :)

Glad to hear you are finding good use from the plugin. As a fellow Django engineer I understand your pain. What I would probably do is create a separate dictionary for Django named `django.txt` where you can add all the words related to django there. I can then add options to selectively enable or disable the dictionary within the plugin (as well as more optional dictionaries in the future).

Would you mind opening a PR with all words you have found til now in a new `django.txt` file?

**Comment by MichaelAquilina** [comment]
I've just uploaded `0.11.0` with initial support for optional dictionaries.

Take a look at the README for how to enable to (currently very minimal) in built django dictionary.

Contribute the django words you found to https://github.com/MichaelAquilina/flake8-spellcheck/blob/master/flake8_spellcheck/django.txt so that everyone can benefit from them :)
