### ISSUE TITLE
Ignore punctuation?

### ISSUE THREAD

**Issue by mkinney** [MichaelAquilina/flake8-spellcheck#22]
Is there a way to ignore punctuation?

If I have a line in a python file like this:

`# Tip: Can run try it out using: 'pyinfra @docker/python python.py'`

It complains about these:

```
./examples/python.py:3:1: SC100 Possibly misspelt word: ''pyinfra'
./examples/python.py:3:8: SC100 Possibly misspelt word: 'py''
```

Note the trailing quote on each.

**Comment by MichaelAquilina** [comment]
This should already be working, so this is definitely a bug :)

**Comment by MichaelAquilina** [comment]
Latest release (`0.12.1`) should fix this issue

**Comment by mkinney** [comment]
Thanks! Will give it a try.
