### ISSUE TITLE
the code for ignoring noqa still has issues

### ISSUE THREAD

**Issue by 3n-k1** [MichaelAquilina/flake8-spellcheck#36]
while fighting with mypy, i discovered that the idiomatic way to disable mypy and flake8 for a line is `# type: ignore  # noqa: SC100`, which causes an issue since the comment only recognizes comments that start with "noqa:"

**Comment by MichaelAquilina** [comment]
If I'm understanding correctly this isnt a crash right? Just fails to act correctly in these scenarios

**Comment by 3n-k1** [comment]
that's correct. an example is `# type: ignore  # noqa: W503`, where `noqa` and `W503` are reported as misspellings

here's a regression test, i'll work on this today: https://github.com/3n-k1/flake8-spellcheck/blob/fix-36/tests/test_flake8_spellcheck.py#L120

**Comment by 3n-k1** [comment]
alright i think i found a solution. we can remove the entire end of comment if it ends with `# noqa: [error code]`. we could either use a regex `#[\s]*noqa:[\s]*[\D]+[\d]+`, or write a small parser to match that style of comment and drop it

**Comment by MichaelAquilina** [comment]
Fix released in 0.19.1
