### ISSUE TITLE
IndexError caused by lines containing only "#" characters

### ISSUE THREAD

**Issue by paulovcmedeiros** [MichaelAquilina/flake8-spellcheck#40]
Hi Michael,

I've found that an IndexError exception is raised, at [line 173](https://github.com/MichaelAquilina/flake8-spellcheck/blob/c7efb5a3546e8a814da55d900ddbeaa147f4e941/flake8_spellcheck/__init__.py#L173) of the flake8_spellcheck/\_\_init\_\_.py file, whenever a commend consisting only of "#" characters is found (e.g., "#######"). This issue is similar to issue #34.

I replaced [line 171](https://github.com/MichaelAquilina/flake8-spellcheck/blob/c7efb5a3546e8a814da55d900ddbeaa147f4e941/flake8_spellcheck/__init__.py#L171) with

`and token_info.string.lstrip("#").strip() != ''`

and it seems to have solved this issue while being compatible with your solution to #34.

I'll submit a merge request soon so you can test it further and see if it can be included in some future release.

Cheers,
Paulo.

**Comment by asears** [comment]
This can be repro'd by running flake8-spellcheck on pip repo.

**Comment by MichaelAquilina** [comment]
thanks for reporting the bug! Would you like to give a go at solving it? The issue seems pretty simple to solve so it would be a good first PR if you want to try :)

**Comment by paulovcmedeiros** [comment]
There is a PR already (see #41 )

**Comment by MichaelAquilina** [comment]
Thanks @paulovcmedeiros. Seems like I just did not realise that the PR was updated. I've merged the PR and will upload a new version soon

**Comment by MichaelAquilina** [comment]
fix has been released in [0.20.1](https://pypi.org/project/flake8-spellcheck/0.20.1/)
