### ISSUE TITLE
Inclusive renaming for --whitelist and whitelist.txt

### ISSUE THREAD

**Issue by asears** [MichaelAquilina/flake8-spellcheck#44]
As the spellcheck "whitelist.txt" file is generally a dictionary of allowed terminology within the codebase, could allowdict.txt, allowterm.txt or allowlist.txt be used instead of whitelist naming?

For non-breaking changes, whitelist.txt could remain as a backwards-compatible default and be used in the code but not in the documentation.  A double-default would be required to fall back to the older version.  Terminology used within the project documentation could be the renamed file.

If this is something the projects authors are interested in I could take a crack at making this change.

In either case, as an improvement to the documentation, the readme could note the way to change the default whitelist.txt file using --whitelist parameters.

**Comment by MichaelAquilina** [comment]
I would definitely be up for this and its been at the back of my mind to introduce anyway. I cant give a timeline for when I would have the chance to work on this though.

Would you like to give a go? It shouldnt be too difficult to figure it out :)

**Comment by mt-krainski** [comment]
Hi, do you need support on this one? I recently found this package and I'd be interested in changing the term "whitelist" :) 

I saw some effort done here https://github.com/MichaelAquilina/flake8-spellcheck/pull/55#discussion_r724526011, but it looks like those were not merged? If you have some suggestions how to go about this change, I'm happy to contribute.

**Comment by MichaelAquilina** [comment]
Hello @mt-krainski, reality is I just dropped the ball on those PRs and should follow up on them. I'm happy for you to take help push this forward if you have the motivation to do so :)

I think we could even not worry about backwards compatibility by just marking the next version as a major version change along with a warning in the changelog.

**Comment by mt-krainski** [comment]
I opened https://github.com/MichaelAquilina/flake8-spellcheck/pull/92; I changed the default `whitelist.txt` to now be `.spellcheck-allowlist`. The CLI parameter is now `--spellcheck-allowlist-file`. I also added an option to specify the allowlist directly via CLI or the flake8 configuration file - something I think would be useful for small allowlists. This new parameter is `--spellcheck-allowlist`.

Please let me know if you have any comments, I'm happy to adjust the PR as needed.
