### ISSUE TITLE
Parse "whitelist" option from config

### ISSUE THREAD

**Issue by paulthomson** [MichaelAquilina/flake8-spellcheck#7]
It looks like there is a `--whitelist` option to set the location of the whitelist.txt file, but the option is not picked up from the flake8 config.

https://github.com/MichaelAquilina/flake8-spellcheck/blob/master/flake8_spellcheck/__init__.py#L105

Is it possible to change this? Perhaps you just need to add `parse_from_config=True`?

**Comment by MichaelAquilina** [comment]
That's probably the issue. Would you like to try the change and make a pull request if it works?

**Comment by paulthomson** [comment]
Sure. I tested it and **I confirm that it seems to work**. I have a PR ready. Sorry to be a pain but I am not sure I am allowed to contribute unless you add a `LICENSE` file containing the MIT license text (+ copyright holder(s) and year(s)) so that GitHub picks up the fact that it is under the MIT license. Or of course feel free to make the parse_from_config change yourself. Thanks!

**Comment by MichaelAquilina** [comment]
Sorry about that @paulthomson. Must have forgotten to add it when I initially set this up. The LICENSE file has been added now :0
