### ISSUE TITLE
Allow whitelist in pyproject.toml

### ISSUE THREAD

**Issue by berzi** [MichaelAquilina/flake8-spellcheck#78]
Would it be possible to support adding the whitelist as a configuration option inside pyproject.toml as an alternative to the whitelist.txt file?

I don't want to adopt this plugin if it means increasing the amount of config files in my project.

**Comment by MichaelAquilina** [comment]
Hello @berzi 

I'm fairly certain this would require support from `flake8`'s side rather than the plugin.

Unfortunately this is not the case and there is no indication they are going to change their mind: https://github.com/PyCQA/flake8/issues/234#issuecomment-812800832

**Comment by MichaelAquilina** [comment]
(Closing this as it is not related to the plugin)

**Comment by berzi** [comment]
@MichaelAquilina Flakeheaven enables specifying plugin settings in pyproject.toml even though vanilla flake8 doesn't. Personally i'd be content with having that, as I always use flakeheaven as a wrapper. Would that also not be possible?

**Comment by MichaelAquilina** [comment]
I was not aware of Flakeheaven to be honest! Are you aware of some projects that support flakeheaven you could post about here? I'll check up on what is involved to get it working

**Comment by berzi** [comment]
Plugins such as flake8-pydantic or flake8-mypy can be configured through pyproject.toml thanks to flakeheaven, for example. Nothing that requires separate files such as your whitelist.txt comes to mind though.

But I suspect it would be as easy as supporting a fallback, in case whitelist.txt is not found, of looking for pyproject.toml and a `whitelist` array variable inside the `[tools.flake8-spellcheck]` section or something like that. Just a hunch though; I never developed flake8 plugins and don't know exactly how flakeheaven overrides the config files shenanigans. I have a feeling many plugins it supports don't explicitly do anything to enable it.
